name: Java CI with Maven

# El flujo se ejecutará en cada push o pull request a la rama main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definición de los trabajos
jobs:
  build:
    # El trabajo se ejecuta en un entorno Ubuntu
    runs-on: ubuntu-latest

    # Pasos del trabajo
    steps:
      # Paso 1: Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar JDK 17 (ajusta según tu versión de Java)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      # Paso 3: Configurar Maven Cache para optimizar las instalaciones
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Paso 4: Instalar dependencias y construir el proyecto con Maven
      - name: Build with Maven
        run: mvn clean install

      # Paso 5: Ejecutar las pruebas del proyecto
      - name: Run tests
        run: mvn test
